export const pharmacyData = [
  {
    title: 'Biotin',
    id: 100,
    image: require('../../assets/images/biotin.jpeg'),
    price: 500,
  },
  {
    title: 'Ronirol',
    id: 1,
    image: require('../../assets/images/101.jpeg'),
    price: 350,
  },
  {
    title: 'Olepra',
    id: 2,
    image: require('../../assets/images/102.jpeg'),
    price: 100,
  },
  {
    title: 'Qusel 100mg',
    id: 3,
    image: require('../../assets/images/103.jpeg'),
    price: 140,
  },
  {
    title: 'Qusel 25mg',
    id: 4,
    image: require('../../assets/images/104.jpeg'),
    price: 80,
  },
  {
    title: 'Prozac',
    id: 5,
    image: require('../../assets/images/105.jpeg'),
    price: 190,
  },
  {
    title: 'SERT',
    id: 6,
    image: require('../../assets/images/106.jpeg'),
    price: 120,
  },
  {
    title: 'Seroxat',
    id: 7,
    image: require('../../assets/images/107.jpeg'),
    price: 130,
  },
  {
    title: 'Flux',
    id: 8,
    image: require('../../assets/images/108.jpeg'),
    price: 180,
  },
  {
    title: 'Dulan',
    id: 9,
    image: require('../../assets/images/109.jpeg'),
    price: 170,
  },
  {
    title: 'Dynetic',
    id: 10,
    image: require('../../assets/images/110.jpeg'),
    price: 250,
  },
  {
    title: 'Galvus Met',
    id: 11,
    image: require('../../assets/images/111.jpeg'),
    price: 220,
  },
  {
    title: 'Omega',
    id: 12,
    image: require('../../assets/images/112.jpeg'),
    price: 270,
  },
  {
    title: 'Becefol',
    id: 13,
    image: require('../../assets/images/113.jpeg'),
    price: 300,
  },
  {
    title: 'Navidoxine',
    id: 14,
    image: require('../../assets/images/114.jpeg'),
    price: 330,
  },
  {
    title: 'Cecon 500mg',
    id: 15,
    image: require('../../assets/images/115.jpeg'),
    price: 700,
  },
  {
    title: 'Biflor 250mg',
    id: 16,
    image: require('../../assets/images/116.jpeg'),
    price: 630,
  },
  {
    title: 'Surbex T',
    id: 17,
    image: require('../../assets/images/117.jpeg'),
    price: 430,
  },
  {
    title: 'Protium',
    id: 18,
    image: require('../../assets/images/118.jpeg'),
    price: 260,
  },
  {
    title: 'Onset 8mg',
    id: 19,
    image: require('../../assets/images/119.jpeg'),
    price: 140,
  },
  {
    title: 'Co Q-10',
    id: 20,
    image: require('../../assets/images/120.jpeg'),
    price: 640,
  },
  {
    title: 'Surbex Z',
    id: 21,
    image: require('../../assets/images/121.jpeg'),
    price: 180,
  },
  {
    title: 'Brexin',
    id: 22,
    image: require('../../assets/images/122.jpeg'),
    price: 180,
  },
  {
    title: 'Plended',
    id: 23,
    image: require('../../assets/images/123.jpeg'),
    price: 100,
  },
  {
    title: 'Omnitor',
    id: 24,
    image: require('../../assets/images/124.jpeg'),
    price: 114,
  },
  {
    title: 'Fenoget',
    id: 25,
    image: require('../../assets/images/125.jpeg'),
    price: 137,
  },
  {
    title: 'Rovista',
    id: 26,
    image: require('../../assets/images/126.jpeg'),
    price: 160,
  },
  {
    title: 'Tritace',
    id: 27,
    image: require('../../assets/images/127.jpeg'),
    price: 195,
  },
  {
    title: 'Sofvasc',
    id: 28,
    image: require('../../assets/images/128.jpeg'),
    price: 65,
  },
  {
    title: 'Lipiget',
    id: 29,
    image: require('../../assets/images/129.jpeg'),
    price: 95,
  },
  {
    title: 'Coaprovel',
    id: 30,
    image: require('../../assets/images/130.jpeg'),
    price: 210,
  },
  {
    title: 'Tenormin',
    id: 31,
    image: require('../../assets/images/131.jpeg'),
    price: 192,
  },
  {
    title: 'Herbesser',
    id: 32,
    image: require('../../assets/images/132.jpeg'),
    price: 198,
  },
  {
    title: 'Disprin',
    id: 33,
    image: require('../../assets/images/133.jpeg'),
    price: 40,
  },
  {
    title: 'Rubifer',
    id: 34,
    image: require('../../assets/images/134.jpeg'),
    price: 70,
  },
  {
    title: 'Xcept',
    id: 35,
    image: require('../../assets/images/135.jpeg'),
    price: 80,
  },
  {
    title: 'Iberet 500',
    id: 36,
    image: require('../../assets/images/136.jpeg'),
    price: 280,
  },
  {
    title: 'Ferosoft',
    id: 40,
    image: require('../../assets/images/140.jpeg'),
    price: 480,
  },
  {
    title: 'Xarelto',
    id: 41,
    image: require('../../assets/images/141.jpeg'),
    price: 130,
  },
  {
    title: 'platlo',
    id: 42,
    image: require('../../assets/images/142.jpeg'),
    price: 135,
  },
];
